name: Pull Request Check

on: 
  pull_request:
    branches:
      - main

jobs:
  TestSpaceJammers:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: astral-sh/ruff-action@v2
          with:
            src: "./src"
